### PR TITLE
FEAT: Added a notebook execution pipeline destined for pdf

### PR DESCRIPTION
**Pull request by AakashGfude**
added a `pdf` target in makefile for images to be in markdown format. 
`make pdf parallel=$(cores)` will run it in parallel
`make pdf` -  will run it sequentially

### CODE REVIEW

**Comment by mmcky** [comment]
this will need to wait until `sphinxcontrib-jupyter=0.5.0` is released to support `pdf` compilation

**Comment by AnjuJoon** [comment]
Thanks @AakashGfude and @arnavs

**Comment by mmcky** [comment]
This is for @AnjuJoon to work with `ipynb_pdf_constructor` for manually building `pdf` files. 
@arnavs this shouldn't be merged as @AnjuJoon can work from this branch. 

We will setup a new branch for upcoming `pdf` support in `sphinxcontrib-jupyter=0.5.0`

**Comment by mmcky** [comment]
this can be closed as no longer relevant given PR #701

**Pull request closed without merging**
