### PR TITLE
"Version Control" Lecture

### PR DESCRIPTION
**Pull request by arnavs**
First pass. Creating a PR per @jlperla in #194. Will delete this from `master` as well

### CODE REVIEW

**Comment by jlperla** [comment]
GitHub Desktop + GitHub Website for dummies.
- Only things they really need to do as beginners collaborating on a project
- At the end, can show screenshots of simple PR for an open-source project

**Comment by jlperla** [comment]
For screenshots:  As you go through, take many more that you think you will really need, because it will be hard to fill in the blanks otherwise if we decide things are unclear:
* In the early parts, Expectations are a good choice, but nothing about PRs (until the Open Source section)
* Creating a new example private repo called `ExampleProject` or something like that
* We can also use the lectures repo as well for screen shots, though there is a lot of noise.

**Comment by arnavs** [comment]
@jlperla I think this is about ready for you to review, modulo stuff like image sizes. It could be that I went overkill on the screenshots as you suggested.

**Comment by jlperla** [comment]
A few modifications/fixes to do:
Not sure what went wrong, but can't see the screenshots.   Maybe move them up from the `/git` subdirectory for consistency with the other static assets... whether it fixes it or not.

Why don't add in a simple "git commandline basics" for people, since this stuff comes up?  My suggestion would be just the following:
- [ ] Explain how to get the Git Bash in windows (I am not sure a screenshot is necessary, but you could
- [ ] Tell them they they can use `cd` and `ls`, and simple linux commands
- [ ] Tell them how to clone, maybe with some example repo? (preferably not something attached to one of our accounts, but that is OK if necessary)  I bet there is some standard git one they use for the docs?
- [ ] Tell them how to pull, i.e. `cd` into the folder, then `git pull`
- [ ] Tell them how to do the hard reset, i.e. the `git fetch origin; git reset --hard HEAD; git pull`
- [ ] I think we should avoid telling them how to commit/add/etc., but you have those links to give them.

**Comment by jlperla** [comment]
I think we should avoid telling them to clone manually any Julia package (e.g. Expectations.jl) in case they get confused.  One thing we could do is add in an example github repo on the QuantEcon organization?

I would prefer a name less generic than `git-setup`.  Maybe we could do the workflow with one called `QuantEcon/example_repository`?  Would it be hard to redo the screenshots where they are not connected to your personal account?  I think it would look more professional when the v1.0 of QE is released, and would allow us to keep those repos permanent?  Doing the fork step to the ubcecon is OK, since we need at least one other org/account to do it.

**Comment by arnavs** [comment]
Modifications sound great. Will flatten the figures directory (although we should eventually pin down why it works on local machines but fails on the syzygy).

As for the screenshots, it took a while to make them, but I see your point. If I could get repo access to QuantEcon, then maybe over the weekend I could reproduce them.

**Comment by jlperla** [comment]
After we redo the screenshots, maybe it makes sense to show a screenshot of the github issues link: https://github.com/issues for the test user, where we have shown them post and assigned an issue... or something like that.

**Comment by arnavs** [comment]
@jlperla Put in a few words about the command line under the "additional resources/troubleshooting." The only other command I added was `git clean -fd` to remove untracked files and dirs.

**Comment by arnavs** [comment]
@jlperla Changes look good to me. Merging now.

**Pull request merged**
