### PR TITLE
RW Uncertainty_Traps (Parameters)

### PR DESCRIPTION
**Pull request by Nosferican**
- This one keeps the `mutable struct` since the code goes pretty well with an `update!` function.
- Please check the before last plot as from the transition from Gadfly it looks different.

### CODE REVIEW

**Comment by jlperla** [comment]
I took at look at the code.   I don't think we should be using mutable structs here, and reorganizing it is worth it.

**Comment by jlperla** [comment]
Another thing on this: I think we should be willing to use dataframes more often than we have. Pushing things onto dataframes, as we calculate, might help things.

One of the great things about dataframes is you can push a named tuple onto them. It is pretty slick.

**Comment by jlperla** [comment]
Except that the whole lecture is basically about doing a simulation of a process and then plotting the results from a dataframe.

If that is what we are doing, then pushing things onto the dataframe as we do a calculation isn't the worst idea.  Regardless, I really don't like mutable structs in this case.

**Comment by arnavs** [comment]
@Nosferican Do you have the bandwidth right now to work on this, or should I take a pass

**Comment by Nosferican** [comment]
Go for it. I still think this is a nice case for mutable structs, but curious to see how you come up with a different approach.

**Comment by jlperla** [comment]
This can wait. It works, and there are plenty of other things to work on

**Comment by arnavs** [comment]
Sounds good @jlperla. Then I suggest merging this (because it contains a lot of other improvements) and revisiting the `mutable struct` later. Also helps cut down on the number of active branches :)

**Pull request merged**
