### PR TITLE
Just for assignment 7

### PR DESCRIPTION
**Pull request by AAdibnia**
In one of the lines you need to use ';'.

### CODE REVIEW

**Comment by jlperla** [comment]
Thanks @AAdibnia   I will close because I think you had done a fork on an earlier version, and some crazy stuff happened!

**Comment by AAdibnia** [comment]
Hi Jessi,

Sorry about that, I am wondering is it enough for part 2a and 2b, or should
I do more?

Thanks
Ali

**Comment by jlperla** [comment]
That is fine.  But if you ever see hundreds of files modified in a PR, then you have done somehting wrong (e.g. chosen to make changes to a particular branch, etc.)

**Comment by AAdibnia** [comment]
Oh, I see thanks for this information.

**Pull request closed without merging**
