### PR TITLE
"Unit Testing" Lecture

### PR DESCRIPTION
**Pull request by arnavs**
Not done yet.

### CODE REVIEW

**Comment by jlperla** [comment]
**Title:** Packages, Testing, and Continuous-Integration

Walkthrough of creating an example package for your own use

* Create the basic project
* After it is created, immediately show people how to get it into a new repo online using GitHub desktop
* Show how to run the code, activate, etc.
* Check in the Manifest/Project so it is reproducible

How to create:
* Try https://github.com/invenia/PkgTemplates.jl
* If it works, add it to QEALP
* Set the name, license, and 
```
julia> t = Template(;
           license="ISC",
           plugins=[
               TravisCI(),
               CodeCov(),
               Coveralls(),
               AppVeyor()
           ],
       )
```
* Call the example package: `ExamplePackage.jl`  use the qeuser account
  * Setup Travis now or later?  Link to the travis setup.
* Tell people the basic structure of the tree of files.
* Code writing workflow
  * What is the workflow to write code?  Startup you go `activate`, where to write code, etc.
  * Tell people to work in the the tests, and put the reusable functions in the src.
  * Tell people to create a jupyter notebook in the main directory.  Could be tracked or not.  Show people you to do the `using` in that notebook.  Then you can play around with the plotting/etc. and call reusable functions
* How does someone else get the project
  * `] dev http://////`
  * Then add it to github desktop by drag/drop
* Unit tests
  * Explain where to put them.
  * Show calling a foo function in the src and testing the output.
  * Explain the `] test` to run
  * Point out testsets and other features
* Continuous Integration
  * Show them how to setup travis.  You might need to point them towards signing up for Travis.
  * Skip appveyor setup for now
  * Skip code coverage setup.
  * Show a screenshot of a build in process (and maybe a link to the existing one)
  * Show how to put the badge up.
  * Show how to `1 == 2` assertion in the test, and what it does in the build

**Comment by jlperla** [comment]
The more I think about it, the more I want to introduce code coverage here.  Lets remove  Coveralls(), just to keep things simple.  And perhaps even AppVeyor is not work the trouble if we don't introduce it.  So it would be
```
plugins=[TravisCI(), CodeCov()],
```

Then, I think we should have in the indstuctions of code coverage for people to:
* Sign in with their GitHub account, and ensure they have already applied for the Student Developer Pack, etc.
* Then  codecov.io  to sign up for CodeCov with it.
* I cannot do this myself since I don't have a student developer account, but if you could do it yourself and then detail the setup steps, it would help a lot.
  * One of the steps will be to five CodeCov access permissions to your repo. 
* After that, in the CI setup section, we can
  * Turn on code coverage for your repo (assuming the setup steps above work)
  * Add a code coverage badge
  * Show people an example with imperfect code coverage.  The best thing to do is to have a `bar()` function in the example package that we don't call in our first unit test.  Then we get a snapshot of the code coverage perfect, then add a test to call `bar()`, etc.

Sounds like we can tell people to sign up for CodeCov

**Comment by Nosferican** [comment]
Most projects I suspect will be public so no need for the Student Developer Pack... CodeCov is free for public / open-source projects. Code coverage last time I check still had some issues being worked on for Julia 1.0.

**Comment by jlperla** [comment]
Not a chance.  Most students are going to want to do their work in private repos because they are ashamed of the code, and because they don't want anyone "stealing their stuff".  Only later would they get enough confidence to work in the open.  We are not talking about writing open-source packages here, just user projects.

If the CodeCov output is imperfect, that is fine, just as long as the setup instructions are solid.

**Comment by jlperla** [comment]
As part of the workflow, you may need to click "Settings/Integrations & services" on the github webpage for the project.  Also, the badges aren't working and I am not sure why.... there must be a missing step.

**Comment by arnavs** [comment]
Merging ahead of lecture tomorrow.

**Pull request merged**
