### PR TITLE
Small modifications to Example: Variations on Fixed Points

### PR DESCRIPTION
**Pull request by sgjanssens**

### CODE REVIEW

**Comment by jlperla** [comment]
Great, thanks so much!

**Review by arnavs — APPROVED** [review]

**Comment by sgjanssens** [comment]
It would probably have been better if this had been a draft to begin with, sorry.
The PR is complete now. Thank you for reviewing it so far!

**Comment by jlperla** [comment]
Thank you so much.  I am planning to push through a bunch of changes later in the month and will finalize the review then.

**Comment by sgjanssens** [comment]
If you are interested in this and #875 in the future, let me know and I will re-open.

**Pull request closed without merging**
