### PR TITLE
"Plots" Lecture

### PR DESCRIPTION
**Pull request by arnavs**
WIP.

### CODE REVIEW

**Comment by arnavs** [comment]
@jlperla Not urgent, but what do you think about adding `UnicodePlots` to this setup? In terms of playing around with stuff from a REPL or something, the convenience and speed is miles ahead of the rest.

**Comment by jlperla** [comment]
For sure when we get to this document.  It is pretty cool.

**Comment by arnavs** [comment]
Just writing this down so it's not forgotten, but could also be worth investigating `https://github.com/JuliaPlots/Makie.jl` Apparently it's the shiny new thing in terms of Julia visualization, and the plots look fantastic.

**Comment by jlperla** [comment]
I am removing for now.  Vegalite and others are emerging.... and recipes are an essential part of the plots ecosystem.

**Pull request closed without merging**
