### PR TITLE
Missing comma

### PR DESCRIPTION
**Pull request by AliKarimirad**
There is a missing comma after lecture "in this lecture we ...."

### CODE REVIEW

**Comment by jlperla** [comment]
@AliKarimirad  Thanks.  I will close this since you accidentally forked a different branch than master (hence all of the enormous number of changes this has listed).

**Comment by AliKarimirad** [comment]
Oh, I am so sorry.
I forked from https://github.com/QuantEcon/lecture-source-jl
Can I continue to commit and push in Exercise 2.b?
*Ali *

**Comment by jlperla** [comment]
I think your fork is fine, but somehow you accidentally made the changes to the "RW-Finite-Markov" branch or something like that?

I would remove your branch, delete your fork, and continue on Exercise 2.b again after repeating.  If there is more than a few "files" listed in the changes, you have done something wrong.

**Comment by AliKarimirad** [comment]
Thanks.

*Ali KarimiradPhD student at University of British Columbia. *
*Email: a.karimirad@a <akarimir@asu.edu>lumni.ubc.ca <http://lumni.ubc.ca>*

**Pull request closed without merging**
