### PR TITLE
Remove static files

### PR DESCRIPTION
**Pull request by XiaojunGuan**
WIP

### CODE REVIEW

**Comment by arnavs** [comment]
@XiaojunGuan Is there any work left on this?

**Comment by XiaojunGuan** [comment]
@arnavs Yes. I'll try to finish this by tomorrow.

**Comment by arnavs** [comment]
RIP

(Sounds great though, no rush.)

**Comment by XiaojunGuan** [comment]
It's done and ready for review

**Comment by arnavs** [comment]
Thanks Xiaojun, I will take a look.

**Comment by arnavs** [comment]
Looks good to me.

**Pull request merged**
