### PR TITLE
Arma plots

### PR DESCRIPTION
**Pull request by ajozefiak**
After completing this one I've realized that the last segment of plotting could be somewhat simplified. Potentially this simplification could be performed later?

### CODE REVIEW

**Comment by jlperla** [comment]
I guess it depends on how much they would be simplified.  If you think that it would make the code much more clear, then it may be worth doing sooner rather than later.  My main worry would be forgetting about it.

Can you create a new issue (or add to the existing metaissue) with a checklist of the ones you want to review, and a note on the change you would intend to make?

**Comment by arnavs** [comment]
@ajozefiak Just want to confirm that you're not proposing structural changes to code (for example, a lot of our plots are wrapped inside kind of opaque plotting functions like `gen_plots`, and maybe it would be clearer to take them out). Because I think that kind of stuff we can hold off on until we start refactoring in earnest. 

But, like @jlperla said, I don't see any reason not to make any other quick fixes.

**Comment by ajozefiak** [comment]
@arnavs The last snippet of code has functions like plot_simulation and these seem a bit excessive for this one lecture. I can hold off on any such structural changes, but this was one particular lecture that stood out to me.

**Comment by jlperla** [comment]
For sure. I think that kind of excessive complexity will be fixed in the rewriting pass

**Comment by arnavs** [comment]
Plots look great, merging now.

**Pull request merged**
